title: Haviedz Miftah
description: "segala yang saya tulis"
logo_img: "/assets/img/favicon.png"
profile_img: "/assets/img/favicon.png"

# Social Links
email: haviedzmiftah@gmail.com
github_username: haviedzmiftah
twitter_username: haviedzmiftah
instagram_username: haviedzmiftah
linkedin_username: haviedzmiftah
facebook_username: havied2

# External API
giscus_repo: "haviedzmiftah/blog"
giscus_repoId: "R_kgDOOO8r_g"
giscus_category: "General"
giscus_categoryId: "DIC_kwDOOO8r_s4CopCO"
goatcounter_code: 
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl: /blog

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
